### ISSUE TITLE
Support additional assume role policy conditions

### ISSUE THREAD

**Issue by mxk** [terraform-aws-modules/terraform-aws-eks-pod-identity#11]
## Is your request related to a problem? Please describe.

EKS Pod Identities documentation recommends including conditions like `aws:SourceOrgId` or `aws:SourceArn` on the IAM assume role policy (examples [here](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#working-with-iam-roles-for-eks-pod-identities) and [here](https://aws.amazon.com/blogs/containers/amazon-eks-pod-identity-a-new-way-for-applications-on-eks-to-obtain-iam-credentials/)). The [current policy](https://github.com/terraform-aws-modules/terraform-aws-eks-pod-identity/blob/ea4ae5e690ad95a8c4a39e131ab9b0d4faff20f1/main.tf#L11-L25) allows defining additional dynamic statements, but the statement for `pods.eks.amazonaws.com` service has no conditions. This is preventing us from restricting roles to specific EKS clusters.

## Describe the solution you'd like.

Allow providing cluster ARN and other conditions to restrict role access.

**Comment by bryantbiggs** [comment]
> This is preventing us from restricting roles to specific EKS clusters.

Could you elaborate on this a bit

**Comment by mxk** [comment]
A role created with the current policy can be assumed by any EKS cluster within the account. It would be nice to be able to add extra conditions to restrict access. To be honest, I don't fully understand the explanation about `aws:SourceOrgId` since the documentation says that these roles can only be assumed from the same account, but filtering based on `aws:SourceArn` of the cluster definitely makes sense to me.

**Comment by bryantbiggs** [comment]
I'm not saying we shouldn't add support for the assume role policy conditions, but I don't think that will do what you are trying to achieve. 

> A role created with the current policy can be assumed by any EKS cluster within the account.

I don't believe this is true. If the role is not associated to the cluster through a pod identity association, then the cluster has no knowledge or access to the role. It would limit the use of the role to certain clusters if someone creates the pod identity association. Instead, I think you might be thinking along the lines of session tags withing the IAM policy.

Session tags used in the policies will ensure that ALB controller on cluster A can only modify the resources it created, and not the resources of another ALB controller on cluster B even though they both use the same IAM role. Or even on the same cluster, you could have a custom role that can create/manage S3 buckets but using the namespace and service account session tags you can effectively limit access for team A (`app:team-a`) from team B (`app:team-b`) even though both are utilizing the same role. The session tags supported today with pod identity are:

- `eks-cluster-arn`
- `eks-cluster-name` 
- `kubernetes-namespace` 
- `kubernetes-service-account` 
- `kubernetes-pod-name` 
- `kubernetes-pod-uid`

**Comment by mxk** [comment]
Do you know why the two AWS examples I linked to put extra conditions on that policy? I understand what you're saying with associations being used to control access and I'm also familiar with session tags. I was specifically thinking of having an extra layer of security/sanity-checking to ensure that you couldn't create an association for a role that should only be used from a specific cluster, but now I'm not sure if it's actually needed.

**Comment by bryantbiggs** [comment]
> Do you know why the two AWS examples I linked to put extra conditions on that policy?

Unfortunately, I do not know why. However, we can support it and leave it up to users

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.3.0 :tada:
