### ISSUE TITLE
association_defaults.tags required to be string

### ISSUE THREAD

**Issue by kkopachev** [terraform-aws-modules/terraform-aws-eks-pod-identity#14]
## Description

`var.association_defaults` type requires it to be a map of strings. However, `.tags` is also valid key for the map and its value suppose to be map itself. When setting it to map, terraform input variables validation fails

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 1.4

- Terraform version:
Terraform v1.9.5
on linux_amd64
- Provider version(s):
+ provider registry.terraform.io/alekc/kubectl v2.0.4
+ provider registry.terraform.io/fastly/fastly v5.13.0
+ provider registry.terraform.io/hashicorp/aws v5.65.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/helm v2.15.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.32.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.11.2
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]
```terraform
module "external_secrets_pod_identity" {
  source  = "terraform-aws-modules/eks-pod-identity/aws"
  version = "~> 1.2"

  name = "test"

  attach_aws_lb_controller_policy = true

  # Pod Identity Associations
  association_defaults = {
    namespace       = "my-namespace"
    service_account = "my-service-account"
    tags = {"foo": "bar"}
  }

  associations = {
    one = {
      cluster_name = "my-cluster-name"
    }
  }
}
```

`terraform plan`

## Expected behavior

plan shows no errors

## Actual behavior
Error
```
The given value is not suitable for module.external_secrets_pod_identity.var.association_defaults declared at
│ .terraform/modules/external_secrets_pod_identity/variables.tf:79,1-32: element "tags": string required.
```

## Additional context

Seems like a trivial fix to allow `var.association_defaults` to have `map(any)`. Or define variable type specifying each allowed key and value type, something like this:

```terraform
variable "association_defaults" {
  description = "Default values used across all Pod Identity associations created unless a more specific value is provided"
  type        = object({
    cluster_name = optional(string)
    namespace = optional(string)
    service_account = optional(string)
    tags = optional(map(string))
  })

  default     = null
}
```

**Comment by bryantbiggs** [comment]
I think the issue is in the code you provided. This:

```hcl
tags = {"foo": "bar"}
```

should be:
```hcl
tags = {foo = "bar"}
```

**Comment by kkopachev** [comment]
Same issue with suggested syntax

**Comment by bryantbiggs** [comment]
ohhhhhh, yes this https://github.com/terraform-aws-modules/terraform-aws-eks-pod-identity/blob/28131749c4a5ccef66072238af410ff79a6d1f1e/variables.tf#L81 should be `map(any)` 

Feel free to open a PR and I'll merge it

**Comment by kkopachev** [comment]
would you consider changing the type to object with defined properties?

**Comment by bryantbiggs** [comment]
no, not at this time - we are still getting a feel for those and what value they provide. we only have them on one module so far and its been a bit of a pain - not sure I am seeing the benefits of those yet
