### ISSUE TITLE
feat: add support for `aws_eks_pod_identity_association` 

### ISSUE THREAD

**Issue by hegerdes** [terraform-aws-modules/terraform-aws-eks-pod-identity#3]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: Included since 5.29.0 (November 30, 2023)

## Is your request related to a problem? Please describe.

Currently you can create roles, assume a role policy and add any policy permission to the role. But you still have have to add the `aws_eks_pod_identity_association` separately.  It would be helpful to include this additional step into the module so I can optionally pass in a list of namespaces/service-accounts that get associated with that role.

## Describe the solution you'd like.

Optional input paremeter that takes a list of namespace service-account combinations and creates a `aws_eks_pod_identity_association` for every entry.  
If this is something that will not be supported it should be mentioned in the docs that users have to create that separately.

## Describe alternatives you've considered.

Currently I use the extra resource `aws_eks_pod_identity_association`

```hcl
resource "aws_eks_pod_identity_association" "vpc_cni" {
  cluster_name    = module.eks.cluster_name
  namespace       = "kube-system"
  service_account = "aws-node"
  role_arn        = module.vpc_cni_pod_identity.iam_role_arn
}
```

## Additional context

Thank's so much for this module. Version 1.0 came out just in time and works great.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.1.0 :tada:
