### ISSUE TITLE
Create aws_eks_pod_identity for Karpenter

### ISSUE THREAD

**Issue by matheusmazzoni** [terraform-aws-modules/terraform-aws-eks-pod-identity#6]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: Included since 5.29.0 (November 30, 2023)

## Is your request related to a problem? Please describe.
I think it would be interesting to have a template for karpenter as well. I'm currently updating to version [20.8 of the EKS module](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v20.8.5)  and I wanted to use my karpenter with pod-identity, because my kube-system run in EC2 Nodes. So, I need to make the association and iwould be interesting use this module.

## Describe the solution you'd like.
The idea would just be to create a template with the necessary policy to make the association for karpenter.

## Describe alternatives you've considered.

I see two alternatives:
1. Create an implementation for karpenter here: Make the implementation based on the examples here
2. Modify the karpenter sub-module within eks: Implement pod-identity within the sub-module [terraform-aws-eks/modules/karpenter](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/karpenter)

If you prefer, I can implement on both repos 😄!

**Comment by matheusmazzoni** [comment]
@bryantbiggs and/or @antonbabenko 
Could you verify this issue? Because if you point me in the right direction I can create it either here or in the eks submodule :D

**Comment by bryantbiggs** [comment]
right now the recommendation for `aws_eks_pod_identity_association` with Karpenter is to use the direct resource as needed

**Comment by bryantbiggs** [comment]
the Karpenter sub-module supports creating the association now so closing out this issue https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3031
