### ISSUE TITLE
Constant drift caused by emtpy tags on the aws_eks_pod_identity_association

### ISSUE THREAD

**Issue by shedimonG** [terraform-aws-modules/terraform-aws-eks-pod-identity#7]
## Description

If `var.tags` is not set and `default_tags` are used, every subsequent plan shows the drift trying to re-create the empty tags:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.eks.module.aws_lb_controller_pod_identity.aws_eks_pod_identity_association.this["alb-controller"] will be updated in-place
  ~ resource "aws_eks_pod_identity_association" "this" {
        id              = "a-xxx"
      + tags            = {}
        # (7 unchanged attributes hidden)
    }

  # module.eks.module.ebs_csi_driver_pod_identity.aws_eks_pod_identity_association.this["csi-driver"] will be updated in-place
  ~ resource "aws_eks_pod_identity_association" "this" {
        id              = "a-yyy"
      + tags            = {}
        # (7 unchanged attributes hidden)
    }

  # module.eks.module.ebs_csi_driver_pod_identity.aws_eks_pod_identity_association.this["snapshot-controller"] will be updated in-place
  ~ resource "aws_eks_pod_identity_association" "this" {
        id              = "a-ppp"
      + tags            = {}
        # (7 unchanged attributes hidden)
    }

  # module.eks.module.external_dns_pod_identity.aws_eks_pod_identity_association.this["external-dns"] will be updated in-place
  ~ resource "aws_eks_pod_identity_association" "this" {
        id              = "a-rrr"
      + tags            = {}
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 4 to change, 0 to destroy.
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `1.2.0`

- Terraform version:
Terraform v1.7.4
on darwin_arm64
- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v5.46.0

## Reproduction Code [Required]
```
provider "aws" {
  default_tags {
    tags = local.Tags
  }
}

locals {
  tags = {
    "tag1"  = "eng-value1",
    "tag2"   = "value2",
  }
}
```
```
module "aws_lb_controller_pod_identity" {
  source  = "terraform-aws-modules/eks-pod-identity/aws"
  version = "~> 1.2.0"

  name = "${module.eks.cluster_name}-lb-ctrl"

  attach_aws_lb_controller_policy = true

  associations = {
    alb-controller = {
      cluster_name    = module.eks.cluster_name
      namespace       = "kube-system"
      service_account = "load-balancer-controller"
    }
  }
}
```

Run `terraform plan` or `terraform apply` after the applied terraform

## Expected behavior

No drift

## Actual behavior

TF wants to propagate empty tags block for the resource

**Comment by bryantbiggs** [comment]
please open an issue on the upstream AWS provider - we do not control default tag behavior within modules

**Comment by rgl** [comment]
@bryantbiggs do you have more context about this problem? by any chance, did you open an issue upstream?

**Comment by calvinbui** [comment]
issue opened https://github.com/hashicorp/terraform-provider-aws/issues/37146

**Comment by calvinbui** [comment]
the issue is probably this module in my testing by setting `tags` under `aws_eks_pod_identity_association.this` to:

- `{}` --> drift
- `null` --> no drift
- removed the tag key --> no drift

**Comment by bryantbiggs** [comment]
Nearly every module has we provide has multiple tag variables and they ALL default to an empty map https://github.com/terraform-aws-modules/terraform-aws-eks/blob/afadb14e44d1cdbd852dbae815be377c4034e82a/variables.tf#L10

Why? Because in the past you can't merge with `null` (i.e. - `merge(var.tags, var.specific_tags)`) - haven't tried this on newer Terraform version to see if this has changed. Also, if you set a value `tags = {foo = "bar"}` and then remove those tags from your code, Terraform would not remove the tags from resources unless you provided an empty container (map, list). Again, I haven't checked the latest Terraform core versions but this should not conflict with the provider default tags

**Comment by calvinbui** [comment]
> Nearly every module has we provide has multiple tag variables and they ALL default to an empty map https://github.com/terraform-aws-modules/terraform-aws-eks/blob/afadb14e44d1cdbd852dbae815be377c4034e82a/variables.tf#L10

yeah, which makes this issue even more confusing. i suspect the tag merging ([this line](https://github.com/terraform-aws-modules/terraform-aws-eks-pod-identity/blob/v1.2.0/main.tf#L185)) needs to be looked at.

> Why? Because in the past you can't merge with `null` (i.e. - `merge(var.tags, var.specific_tags)`)

i don't suggest it should default to `null`, only showing no drift occurs. And you're right, you cannot merge null either (example below).

3 of us in this issue have come across this problem. I don't think it's the provider, but the code in this module or how terraform is merging maps.

i've tried a few other things which doesn't work or error as well. 

- Setting `association_defaults.tags` to an empty map

    ```
    │ Error: Invalid value for input variable
    │
    │   on aws-pod-identity.tf line 10, in module "pod_identity":
    │   10:   association_defaults = {
    │   11:     namespace       = helm_release.main.namespace
    │   12:     service_account = local.service_account_name
    │   13:     tags            = {}
    │   14:   }
    │
    │ The given value is not suitable for module.pod_identity.var.association_defaults declared at
    │ .terraform/modules/pod_identity/variables.tf:73,1-32: element "tags" string required.
    ```

- Setting `association_defaults.tags` to null.

    ```
    │ Error: Error in function call
    │
    │   on .terraform/modules/pod_identity/main.tf line 185, in resource "aws_eks_pod_identity_association" "this":
    │  185:   tags = merge(var.tags, try(each.value.tags, var.association_defaults.tags, {}))
    │     ├────────────────
    │     │ while calling merge(maps...)
    │     │ each.value is object with 1 attribute "cluster_name"
    │     │ var.association_defaults.tags is null
    │     │ var.tags is empty map of string
    │
    │ Call to function "merge" failed: arguments must be maps or objects, got "string".
    ```
