### ISSUE TITLE
Have to manually re-create pods to have the expected pod identity environment variables

### ISSUE THREAD

**Issue by rgl** [terraform-aws-modules/terraform-aws-eks-pod-identity#8]
## Description

When configuring the Pod Identity with terraform, it seems there's a race between
creating the `aws_eks_pod_identity_association` and `kubernetes_deployment_v1`
(and any resource that (in)directly creates Pods) resources. The created pod
ends up not having the required environment variables that allow it to
actually have a Pod Identity.

When the Pod does not have the `AWS_CONTAINER_CREDENTIALS_FULL_URI` and
`AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` environment variables, we must, manually,
re-create the pod, and hope for the best.

See [How EKS Pod Identity works](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-how-it-works.html).

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 1.2.0

- Terraform version: 1.8.2
```
Terraform v1.8.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.47.0
+ provider registry.terraform.io/hashicorp/helm v2.13.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.29.0
```

## Reproduction Code [Required]

**NB** This code is an abbreviated version of the code at the branch at https://github.com/rgl/terramate-aws-eks-example/tree/pod-identity.

```hcl
# see https://registry.terraform.io/modules/terraform-aws-modules/eks-pod-identity/aws
# see https://github.com/terraform-aws-modules/terraform-aws-eks-pod-identity
module "aws_eks_pod_identity_kubernetes_hello" {
  source  = "terraform-aws-modules/eks-pod-identity/aws"
  version = "1.2.0"

  name = "${data.aws_eks_cluster.eks.id}-${kubernetes_service_v1.kubernetes_hello.metadata[0].name}"
  associations = {
    kubernetes_hello = {
      cluster_name    = data.aws_eks_cluster.eks.id
      namespace       = "default"
      service_account = kubernetes_service_v1.kubernetes_hello.metadata[0].name
    }
  }
  attach_custom_policy = true
  policy_statements = [
    {
      sid = "Route53"
      actions = [
        "route53:Get*",
        "route53:List*",
        "route53:TestDNSAnswer",
      ]
      resources = ["*"]
    }
  ]
}

resource "kubernetes_deployment_v1" "kubernetes_hello" {
  metadata {
    name = "kubernetes-hello"
  ...
  depends_on = [
    module.aws_eks_pod_identity_kubernetes_hello,
  ]
}
```

1. create both resources from above.
2. notice there are no `AWS_*` (e.g. `AWS_CONTAINER_CREDENTIALS_FULL_URI`) environment variables with: `kubectl get pods -l app=kubernetes-hello -o yaml | grep -A 1 AWS_`
3. re-create the deployment/pods with thew following, and notice that it now has the expected `AWS_` environment variables:
```bash
# delete the pods and wait for them to be re-deployed.
kubectl delete pods -l app=kubernetes-hello
kubectl rollout status deployment kubernetes-hello
# check whether the required Pod Identity environment variables are listed.
# they should be, at least, the following:
#   AWS_CONTAINER_CREDENTIALS_FULL_URI
#   AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
kubectl get pods -l app=kubernetes-hello -o yaml | grep -A 1 AWS_
```

## Expected behavior

Expected the environment variables to be available.

## Actual behavior

There are no Pod Identity related environment variables available.

**Comment by bryantbiggs** [comment]
correct - the association would need to be created before the pods are deployed. this is also applicable to those migrating from IRSA to pod identity - after you create the pod identity association, you will need to bound the pods so they pick up the new creds using pod identity

closing for now since there isn't anything that this module can do to resolve this - its just part of the ordering and lifecycle of events

**Comment by rgl** [comment]
Have you noticed that's what being done above?

It seems the `module "aws_eks_pod_identity_kubernetes_hello"` should not have being marked as "done" until the associations actually complete?

Without that, how do you expect one to known that the Pod Identity is ready to be used and we can actually create the Pod?

**Comment by rgl** [comment]
Indeed, it's async, but for being used in terraform this provider/module must have a way to wait for it to actually finish. Turning it in a sync operation from the terraform viewpoint. Otherwise how do we create the pod identify and actually use it a pod when using terraform?

**Comment by rgl** [comment]
Ping?
